hello: hello
spring:
  h2:
    console:
      enabled: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  datasource:
    username: mfine
    password: 123456
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;MODE=MySQL
    driver-class-name: org.h2.Driver
    schema: classpath:schema.sql
    data: classpath:data.sql
pagehelper:
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  helper-dialect: mysql


mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.df.pojo

logging:
  level:
    com.df.mapper: debug
server:
  port: 5000




